### ISSUE TITLE
Minimum PHP Version

### ISSUE THREAD

**Issue by hubtraum** [finalbytes/google-distance-matrix-api#1]
The minimum PHP version is not 7.0 as stated in the readme, it is 7.1 because of the used _void return type_:

http://php.net/manual/de/migration71.new-features.php

Maybe just a small detail but it costs quote some time for debugging to find out why this tiny and useful library silently fails on loading (error log was empty....).

**Comment by michaelrachlitz** [comment]
@finalbytes please correct this.

**Comment by finalbytes** [comment]
Fixed!
